apiVersion: v1
kind: Pod
metadata:
  name: label-demo-3
  labels:
    env: prod
    app: nginx
    version: "1.14.2"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80