apiVersion: v1
kind: Pod
metadata:
  name: radial-busybox
spec:
  containers:
  - name: radial-busybox
    image: radial/busyboxplus
    command:
    - 'sleep'
    - '1000'
    securityContext:
      runAsUser: 1000
      #redundant as 1000 is not root but good to have
      #as the runtime will do verification that no process will
      #run as root within the container
      runAsNonRoot: true